# Site settings
title: Lemon Blog
SEOTitle: Lemon Blog | 柠檬的博客 
header-img: img/home-bg.jpg
email: gdut.lemon@gmail.com
description: "to share my android-learning expericences| 安卓技术、资源交流和分享"
keyword: "lemon,lemon-yang,gdut,gdut-lemon,gdutlemon,android,柠檬,杨杰豪,安卓,广工"
url: "http://gdut-lemon.cc"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
google_username:    "112661216545638145910"
github_username:    lemon-yang
twitter_username:   GdutLemon
facebook_username:  gdut.lemon



# Build settings
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: lemon

# Duoshuo settings
#duoshuo_username: lemon
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: gdut-lemon.cc



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "你不会找到路，除非你敢于迷路"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


